version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dockerusers
      MYSQL_USER: user
      MYSQL_PASSWORD: DB_PASSWORD
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  
