name: laravelapp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t tidianeka/laravelapp:latest .

      - name: Push to Docker Hub
        run: docker push your-docker-username/laravelapp:latest
